import {
  html,
  css,
  photoshop,
  react,
  figma,
  lightroom,
  illustrator,
  js,
  mobileapp,
  mobileappview,
  jwview,
  listapp2,
  listapp3,
  listapp4,
  listapp5,
  listapp6,
  listapp7,
  jwproject,
  pjcbg,
  p1,
  p2,
  p3,
  p4,
  p5,
} from "../assets/index";

export const skills = [
  { name: "Photoshop", icon: photoshop, stars: "4" },
  { name: "FigmaL", icon: figma, stars: "3" },
  { name: "HTML", icon: html, stars: "4" },
  { name: "CSS", icon: css, stars: "4" },
  { name: "React", icon: react, stars: "1" },
  { name: "React Native", icon: react, stars: "3" },
  { name: "Lightroom", icon: lightroom, stars: "3" },
  { name: "Illustrator", icon: illustrator, stars: "3" },
  { name: "Javascript", icon: js, stars: "3" },
];

export const projects = [
  {
    title: `Mobile Application`,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolor Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolor Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolor Lorem ipsum dolor sit amet, consectetur adipiscing elitsed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    tools: "React Native | JavaScript | SQL",
    mainphoto: mobileapp,
    viewphoto: mobileappview,
    photos: [
      { name: "listapp2", icon: listapp2 },
      { name: "listapp3", icon: listapp3 },
      { name: "listapp4", icon: listapp4 },
      { name: "listapp5", icon: listapp5 },
      { name: "listapp6", icon: listapp6 },
      { name: "listapp7", icon: listapp7 },
    ],
  },
  {
    title: `Portfolio`,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    tools: "HTML | CSS | React",
    mainphoto: listapp2,
    photos: [
      { name: "listapp1", icon: listapp2 },
      { name: "listapp2", icon: listapp2 },
      { name: "listapp3", icon: listapp3 },
      { name: "listapp4", icon: listapp4 },
      { name: "listapp5", icon: listapp5 },
      { name: "listapp6", icon: listapp6 },
      { name: "listapp7", icon: listapp7 },
    ],
  },
  {
    title: `Web/Shop Project`,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    tools: "Photoshop | Figma",
    mainphoto: jwproject,
    viewphoto: jwview,
    photos: [
      { name: "listapp1", icon: listapp2 },
      { name: "listapp2", icon: listapp2 },
      { name: "listapp3", icon: listapp3 },
      { name: "listapp4", icon: listapp4 },
      { name: "listapp5", icon: listapp5 },
      { name: "listapp6", icon: listapp6 },
      { name: "listapp7", icon: listapp7 },
    ],
  },
  {
    title: `app2`,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    tools: "frgthyjukjhgfd",
    mainphoto: listapp2,
    photos: [
      { name: "listapp1", icon: listapp2 },
      { name: "listapp2", icon: listapp2 },
      { name: "listapp3", icon: listapp3 },
      { name: "listapp4", icon: listapp4 },
      { name: "listapp5", icon: listapp5 },
      { name: "listapp6", icon: listapp6 },
      { name: "listapp7", icon: listapp7 },
    ],
  },
];

export const gallery = [
  pjcbg,
  p1,
  html,
  pjcbg,
  p3,
  pjcbg,
  p4,
  pjcbg,
  pjcbg,
  p5,
  figma,
  react,
  photoshop,
  pjcbg,
  p5,
  pjcbg,
  css,
  p2,
];
